### ISSUE TITLE
针对域名的鉴权逻辑支持类型不足

### ISSUE THREAD

**Issue by happybeta** [tal-tech/conan#15]
当前的Web系统的认证类型较多，当前的系统仅仅支持 采用 header里 使用 Cookie的类型的。
比如我的产品使用了AKSK认证。 是在header中增加了Authorization参数。且认证逻辑比较复杂。 

[AKSK认证信息]参考 https://support.huaweicloud.com/devg-apisign/api-sign-provide-aksk.html

**Comment by saviorghost** [comment]
鉴权这部分逻辑确实不是很通用并且存在安全风险，还是建议大家自己实现。后续我们可能会上线对groovy语言的支持，可以通过脚本实现。
