### ISSUE TITLE
怎么录制回放带有 queryString 的 get 接口？

### ISSUE THREAD

**Issue by chenhengjie123** [tal-tech/conan#18]
在接口管理里配置的接口名称：`/api/case/list`

在 域名管理中的 es 配置：

ES中_source内接口名称对应的原始值：`GET /api/case/list?pageSize=10&pageNum=1&productLineId=1&caseType=0&channel=1&bizId=83b0bcf4`

接口正则表达式：`/.*(?=\?)`

录制完毕后，回放时，提示如下错误：

```
2021-06-22 05:24:39 [INFO]  --开始执行回放, 回放ID：replay_id=12,task_execution_id=32,record_id=32\n2021-06-22 05:24:44 [INFO]   --回放url=http://127.0.0.1:8094/api/case/list,body=,response={code:10400,msg:Required Integer parameter 'channel' is not present,data:null}
2021-06-22 05:24:44 [INFO]   --回放url=http://127.0.0.1:8094/api/case/list,body=,response={code:10400,msg:Required Integer parameter 'channel' is not present,data:null}
...
```

错误原因为 url 里缺失了 queryString 部分。查看源码发现，回放时接口请求完整url拼接逻辑为：

com.tal.wangxiao.conan.agent.service.impl.ReplayServiceImpl#doReplay
```
...
Optional<Api> apiOptional = apiRepository.findById(apiId);
...
String domainName = domainOptional.get().getName();
            String method = EnumUtil.getByField(HttpMethodConstants.class, "getValue", String.valueOf(api.getMethod())).getLabel();
            String urlStr = "http://" + domainName + api.getName();
...
response = replayByHttp(urlStr, method, body, headerMap);
                log.info("回放url={},method={},body={},response={}", urlStr, method, body, response);
```

逻辑里面，url 用的是 api.getName() ，即数据库中的接口名称。这个名称是不会带有 queryString 的，所以导致回放时缺失这部分。

是我使用姿势不对吗？还是目前不支持带有 QueryString 的 Get 接口录制回放？

**Comment by saviorghost** [comment]
hengjie老师，这部分是有处理的，录制时会根据接口名作为条件查询，然后根据es中查询到的日志切割body存到bss_record_result表中，回放时会读取表中数据，可以检查下bss_record_result表中是否有body的数据
![image](https://user-images.githubusercontent.com/30309730/124212439-8d8a8000-db21-11eb-9fbb-c174a5e604bc.png)
![image](https://user-images.githubusercontent.com/30309730/124212506-a5fa9a80-db21-11eb-8267-d9f18e9b5836.png)
