### ISSUE TITLE
启动ConanAdminApplication后报“Table 'conandb.bss_task_schedule' doesn't exist”

### ISSUE THREAD

**Issue by DuanYuePeng** [tal-tech/conan#4]
sql脚本里的表名和代码里的表名是不匹配的，比如脚本里的表是'diff_detail'，代码里的表是'bss_diff_detail'

**Comment by DuanYuePeng** [comment]
sql脚本里的表名和代码里的表名是不匹配的，比如脚本里的表是'diff_detail'，代码里的表是'bss_diff_detail'

**Comment by dazzlingn** [comment]
你是不是导错表了，conan/sql/conan_table_structure_and_test_data_v1.sql
